name: Build Angular Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.13.1'
      - run: npm install
        working-directory: ./Frontend
      - run: npx ng build
        working-directory: ./Frontend
      - run: npx ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./Frontend
        env:
          CI: true
